articles/urls.py
from django.urls import path, include
from .views import index, show_articles, showarticle, show_topics, send_input_data, create_topic, create_article
from .views import show_cat, show_cake, show_socialising, show_computer, show_water,show_weeds

app_name = 'articles'

urlpatterns = [
    path('', index, name='index'),
    path('topics', show_topics, name='topics'),
    path('input', send_input_data, name='input'),
    path('topic/add', create_topic, name='add_topic'),
    path('article/create', create_article, name='create_article'),
    path('article/show', show_articles, name='show_articles'),
    path('cat', show_cat, name='show_cat'),
    path('cake', show_cake, name='show_cake'),
    path('socialising', show_socialising, name='show_socialising'),
    path('computer', show_computer, name='show_computer'),
    path('water', show_water, name='show_underwater'),
    path('weeds', show_weeds, name='show_weeds'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

namespace='blog'

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    topic_name = models.CharField(max_length = 256)

    def __str__(self):
        return self.topic_name

class Article(models.Model):

    title = models.CharField(max_length =256)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE, related_name='articles')
    articleText = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from .models import Article, Topic


class InputForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()

class TopicForm(forms.ModelForm):
    class Meta():
        model = Topic
        fields = ("topic_name",)

class ArticleForm(forms.ModelForm):
    class Meta():
        model = Article
        exclude =['created_at',]

articles/views.py
from django.shortcuts import render, redirect
from .models import Topic, Article #imported
from .forms import InputForm
from . import forms
#from django.http import HttpResponse



#   Create your views here.

def show_computer(request):
    return render(request,'computer.html',{'form':''})

def show_water(request):
    return render(request,'water.html',{'form':''})

def show_weeds(request):
    return render(request,'weeds.html',{'form':''})

def index(request):
    return render(request,'index.html',{'form':''})

def show_cat(request):
    return render(request,'cat.html',{'form':''})

def show_cake(request):
    return render(request,'cake.html',{'form':''})

def show_socialising(request):
    return render(request,'socialising.html',{'form':''})


def create_article(request):
    if request.method == "POST":
        form = forms.ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:topics')
        else:
            print("an error has occured")
    form = forms.ArticleForm()
    return render(request, 'input.html', {'form':form})


def show_articles(request):
    articles = Article.objects.all()
    return render(request, 'index.html', {'articles':articles})



def create_topic(request):
    if request.method == "POST":
        form = forms.TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:topics')
        else:
            print("an error has occured")
    form = forms.TopicForm()
    return render(request, 'input.html', {'form':form})



def send_input_data(request):
    form = InputForm()
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            print("form valid")
        else:
            print("form not valid")
    return render(request,'input.html',{'form':form})



def show_topics(request):
    topics = Topic.objects.all()
    return render(request, 'topics.html', {'topics':topics})



def showarticle(request):
    title="My First Article"
    article="""
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    """
    author = "Matshehla Konaite"
    return render(request, 'blog.html',{'title':title, 'article':article})



#   Create your views here.
# def index(request):
#    return HttpResponse("AppTwo Index view")

articles/templates/admin.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last -->

    <title>Hello, world App</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>Block Contents information
          <a href="{% url 'articles:index' %}" class="btn btn-link">Home</a>
          <a href="admin/" class="btn btn-link">Admin</a>
    </h6>
      </div>
    </div>

    <h1 style="text-align:center">Create a new Article</h1>

    <div class="container">
      <form action="/action_page_process_submitted_data.php">
        <h2>Article Title</h2>
        <input class="form-control" type="text" id="artTtitle" name="" value="">
        <br>
        <h2>Choose an Image</h2>
        <input type="file" id="file" name="" value="">
        <br> <br>
        <h2>Text Area</h2>
        <textarea class="form-control" rows="5" id="artTxt"></textarea>
        <br>
        <h2>Article Category</h2>
        <input class="form-control" type="text" id="artCat" name="" value="">
        <br>
        <button type="submit" class="btn btn-success">Create Article</button>
        <a href="index.html" class="btn btn-secondary">Cancel</a>
      </form>
    </div>
    <br>
    <br>

    <!--Footer -->
    <div class="container-fluid" style="background-color:rgb(10,10,10); margin-bottom:0rem">
      <br>
      <div class="container">
        <h1 style="color: grey">Blogging</h1>
        <p style="color: grey">My perfect blog</p>
        <blockquote class="blockquote">
          <p style="color: grey">For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
          <footer class="blockquote-footer">From WWF's website</footer>
        </blockquote>
      </div>
      <br>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

articles/templates/cake.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog:Django</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>My BLOG </h1>
        <h6>My perfect block
  </h6>
      </div>
    </div>


    <!-- let Bootstrap automatically handle the layout -->

    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-link">Home</a>
      <a href="admin/" class="btn btn-link">Admin</a>
    <br>
      <br>
    </div>


    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/cake.jpg' %}" alt="Card image" style="width:100%">
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Cake</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>
        </div>
      </div>
    </div>

    <br>

    <!--Footer -->
    <div class="container-fluid" style="background-color:rgb(10,10,10); margin-bottom:0rem">
      <br>
      <div class="container">
        <h1 style="color: grey">Blogging</h1>
        <p style="color: grey">My perfect blog</p>
        <blockquote class="blockquote">
          <p style="color: grey">For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
          <footer class="blockquote-footer">From WWF's website</footer>
        </blockquote>
      </div>
      <br>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

articles/templates/computer.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Student Name: Matshehla Mathews Konaite
        Student No: 213659103
        Lecturers: Dr. Kyle Stone and Mark Muwanguzi
        Course: Full Stack Web Development Short Learning Course
        Assignment 2
        Date: 30 October 2022
    -->

    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog:Django</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>My BLOG</h1>
        <h6>My perfect blog</h6>
      </div>
    </div>

    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-link">Home</a>
      <a href="admin/" class="btn btn-link">Admin</a>
    <br>
      <br>
    </div>

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/computer.jpg' %}" alt="Card image" style="width:100%">
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Computer</h2>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>

        </div>
      </div>
    </div>

    <br>

    <!--Footer -->
    <div class="container-fluid" style="background-color:rgb(10,10,10); margin-bottom:0rem">
      <br>
      <div class="container">
        <h1 style="color: grey">Blogging</h1>
        <p style="color: grey">My perfect blog</p>
        <blockquote class="blockquote">
          <p style="color: grey">For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
          <footer class="blockquote-footer">From WWF's website</footer>
        </blockquote>
      </div>
      <br>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

articles/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Django</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>My BLOG</h1>
        <h6>My perfect blog</h6>
      </div>
    </div>

    <br>
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-link">Home</a>
      <a href="admin/" class="btn btn-link">Admin</a>
        <br>
      <br>
    </div>
    <br>
    <!-- let Bootstrap automatically handle the layout -->
    <div class="container-fluid">

      <!-- ROW 1-->
      <div class="row">
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='cat.html'" src="{% static 'images/cat.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Cats</h4>
              <a href="cat" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='cake.html'" src="{% static 'images/cake.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Cakes</h4>
              <a href="cake" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='socialising.html'" src="{% static 'images/socialising.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Socialising</h4>
              <a href="socialising" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
      </div>
      <br>


      <!--  ROW 2 -->
      <div class="row">
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='computer.html'" src="{% static 'images/computer.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Computer</h4>
              <a href="computer" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='water.html'" src="{% static 'images/water.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Water</h4>
              <a href="water" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card" style="width:100%">
            <img class="card-img-top" onclick="location.href='weeds.html'" src="{% static 'images/weeds.jpg' %}" alt="Card image" style="width:100%">
            <div class="card-body">
              <h4 class="card-title">Weeds In the water</h4>
              <a href="weeds" class="btn btn-primary">Continue</a>
            </div>
          </div>
        </div>
      </div>
      <br>

      <br>
    </div>


      <!--Footer -->
      <div class="container-fluid" style="background-color:rgb(10,10,10); margin-bottom:0rem">
        <br>
        <div class="container">
          <h1 style="color: grey">Blogging</h1>
          <p style="color: grey">My perfect blog</p>
          <blockquote class="blockquote">
            <p style="color: grey">For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
            <footer class="blockquote-footer">From WWF's website</footer>
          </blockquote>
        </div>
        <br>
      </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

articles/templates/socialising.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Assignmet 2</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid" style="background-color:blue">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>My perfect blog</h6>
      </div>
    </div>

    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-link">Home</a>
      <a href="admin/" class="btn btn-link">Admin</a>
  <br>
      <br>
    </div>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/socialising.jpg' %}" alt="Card image" style="width:100%">
            </div>
            <br>

          </div>
        </div>
        <div class="col">

          <h2>People Socialising</h2>

          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

            Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>

        </div>
      </div>
    </div>

    <br>

    <!--Footer -->
    <div class="container-fluid" style="background-color:rgb(10,10,10); margin-bottom:0rem">
      <br>
      <div class="container">
        <h1 style="color: grey">Blogging</h1>
        <p style="color: grey">My perfect blog</p>
        <blockquote class="blockquote">
          <p style="color: grey">For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
          <footer class="blockquote-footer">From WWF's website</footer>
        </blockquote>
      </div>
      <br>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>